title: Hello World
author: Igor Shtyk
email: geos79@tut.by
description: > # this means to ignore newlines until "baseurl:"
  This site about woodcraft in Belovezhskaya Puscha

# social links
twitter_username: Vanvala1
github_username:  Vanvala

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
